site_name: COVID19 SEIIR Modeling Pipeline
nav:
	- Getting Started: index.md
theme:
	name: 'material'
	palette:
		primary: 'green'
		accent: 'green'
markdown_extensions:
	- mdx_math
	- admonition
	- codehilite
	- footnotes
	- mkautodoc
