name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7] #, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env_python${{ matrix.python-version }}
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          which conda
          conda list
          which python
