name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7] #, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          conda create -y --name=test_env_python${{ matrix.python-version }} python=${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda init bash
          source /home/runner/.bashrc
          conda activate test_env_python${{ matrix.python-version }}
          which python
          # pip install .[test,docs]
